name = "raft"
main = "src/index.ts"
compatibility_date = "2023-01-27"

[triggers]
crons = ["0 0 * * *"]

[durable_objects]
bindings = [{ name = "nodes", class_name = "Node" }]

[[migrations]]
tag = "v0"
new_classes = ["Node"]
